Er 14 as implement api equipment removal
tranleduyan/ETC-Backend pull request #7
Opened 2024-02-01 01:06 UTC by amansiid

/**
 *  DELETE/EQUIPMENT REMOVE
 *  URL => /api/inventory/remove
 * 
 *      "schoolId": string,
 *      "itemId":  ["serialNum", "serialNum", .....]
 */

This API allows the removal of items from the inventory, single items or multiple. 
The API should return a response message with status 200, indicates the action of removal was successful or return an error message with status 503.

2024-02-04 20:46 UTC, tranleduyan requested changes
After all the changes, you can re test it again.

2024-02-04 20:46 UTC, tranleduyan commented on src_code/src/routes/InventoryRoutes.js
> +module.exports = router;
There is a duplicate.

2024-02-05 02:01 UTC, YiJiePV requested changes
Looking good! Just a couple house-keeping things from my end, and Le's feedback as well. Unfortunately, I cannot test your code as of now, since the error pointed out by Le and myself is causing the error:
![syntax-error](https://github.com/tranleduyan/ETC-Backend/assets/97055517/0168a229-7ef3-4e74-9d51-8eb73a56f2f2)
Once that error's fixed, I'll be able to test your code and make sure that everything works smoothly 👍

2024-02-05 02:01 UTC, YiJiePV commented on src_code/src/controllers/services/Inventory/EquipmentRemoval.js
> + * @param {Object} req - Express request object containing item ID
nit: and school ID??

2024-02-05 02:01 UTC, YiJiePV commented on src_code/src/controllers/services/Inventory/EquipmentRemoval.js
> + * Validates the request parameters for single equipment removal.
nit: this also has the capability for mass delete, right? Update?

2024-02-05 02:01 UTC, YiJiePV commented on src_code/src/controllers/services/Inventory/EquipmentRemoval.js
> +    EquipmentRemovalValidation
Do we really need to export the validation here?

2024-02-05 02:01 UTC, YiJiePV commented on src_code/src/routes/InventoryRoutes.js
> + *      "itemId": serial
This is the request body, right? And any info about the response?

2024-02-05 02:01 UTC, YiJiePV commented on src_code/src/routes/InventoryRoutes.js
> +module.exports = router;
Yep, what Le said. When resolving merge conflicts, don't forget to double check for duplicate code and bad syntax (like the `===` divider) before commiting and pushing the changes 😉 And while at it, don't forget to leave a newline at the end of the files

2024-02-05 02:01 UTC, YiJiePV commented on src_code/src/utils/services/helper_functions/db_helper_functions/item/ItemDBHelperFunction.js
Does this helper serve a purpose? If not, I think it would be wise to delete it.

2024-02-05 02:48 UTC, amansiid commented
I've addressed the requested updates.

2024-02-10 23:14 UTC, leduyantran approved these changes
The code is looking good to me. I tested and it works well.

2024-02-10 23:14 UTC, leduyantran commented on src_code/src/routes/InventoryRoutes.js
> +router.delete('/remove', async(request, response) => {
Why is this change to remove? If you look at the code base logic, all post, delete are in one url. There is no sub endpoint or necessary to create another url. Also, if there is the inventory/remove endpoint does not meaningful to say it is for deleting equipment. The url should be /equipment.  Please update the comment as well.

2024-02-10 23:48 UTC, tranleduyan approved these changes

2024-02-11 01:05 UTC, mohammedking11-spu approved these changes
Overall, it gets my approval. It was easy to follow and well-structured, and the good thing is that it also has enough comments. Looks optimized and works as requested! Great job Aman!

2024-02-11 01:05 UTC, mohammedking11-spu commented on src_code/src/controllers/services/Inventory/EquipmentRemoval.js
Looks easy to follow. I appreciate that you included a comment that shows what the expected request body would look like. It was well-structured, and enough comments to make everything clear and concise. Great job at sticking with the code conventions.

2024-02-11 01:10 UTC, YiJiePV approved these changes
Much better now! Everything's working like they should, I just added a couple minor fixes myself. I'm a little concerned about the fact that there isn't a check for each individual serial ID passed in the array, but since a "item not found" 400 Bad Request is thrown every time I tried that test case, I think it would probably do for now. But besides that, no other issues from my end 👍

2024-02-13 02:30 UTC, merged