ER 180 AS-Export CSV All Equipment API
tranleduyan/ETC-Backend pull request #9
Opened 2024-02-24 00:17 UTC by amansiid

/**
 *  EXPORT CSV/EQUIPMENT EXPORT
 *  URL => /api/inventory/export-csv
 *  requestBody:
 *  {
 *      "schoolId": string
 *  }
 */

Hello Team, the export CSV all equipment API is functioning and outputting the results requested. Please review and let me know of any concerns and adjustments.
![exportresult](https://github.com/tranleduyan/ETC-Backend/assets/83798920/a97cdf9f-2db2-4513-b159-df54cc43d218)

2024-02-25 20:30 UTC, leduyantran requested changes
Need to return with csv file in the response body for communications.

2024-02-25 23:14 UTC, YiJiePV requested changes
Looking good! Just some small things plus the concern Le brought up. Otherwise, I think this looks good, and the validation works like it should. 👍

2024-02-25 23:14 UTC, YiJiePV commented on src_code/src/controllers/services/Inventory/ExportCSV.js
> +        const userValidationMessage = await ValidateUser(schoolId);
nit: redundant `await` on a non-`Promise`
You can change this to `const userValidationMessage = await Promise.resolve(ValidateUser(schoolId));`

2024-02-25 23:14 UTC, YiJiePV commented on src_code/src/controllers/services/Inventory/ExportCSV.js
> +        const validationError = await ValidateItems(inventoryData);
nit: redundant `await` on a non-`Promise`
Same change similar to above, just use a `Promise.resolve()`

2024-02-25 23:14 UTC, YiJiePV commented on src_code/src/controllers/services/Inventory/ExportCSV.js
> +    const user = await dbHelper.GetUserInfoBySchoolId(db, schoolId);
nit: redundant `await` on a non-`Promise`
Similar change to above: use `Promise.resolve()`

2024-02-25 23:14 UTC, YiJiePV commented on src_code/src/controllers/services/Inventory/ExportCSV.js
> +async function ValidateUser(schoolId) {
I'm not sure if you're aware of this, but I've created a general helper function `ValidateAdminUser` for this very purpose. Otherwise, copying/pasting this function over and over again become very, very redundant and wasteful.

2024-02-25 23:14 UTC, YiJiePV commented on equipment.csv
Same comment as Le, I doubt this endpoint is supposed to export to the repo directly. It won't be accessible then.

2024-02-25 23:14 UTC, YiJiePV commented on src_code/src/controllers/services/Inventory/ExportCSV.js
> +            console.log('Equipment data exported to equipment.csv');
What's this console.log for? Is it really necessary?

2024-02-26 01:42 UTC, amansiid commented on src_code/src/controllers/services/Inventory/ExportCSV.js
> +async function ValidateUser(schoolId) {
I'm not aware of that but will address that issue.

2024-02-26 20:27 UTC, leduyantran approved these changes
It looks good! I approved it, Aman!

2024-02-28 17:43 UTC, YiJiePV approved these changes
Looks good now, Aman! Great job 😀

2024-02-28 21:53 UTC, merged